<a href="https://colab.research.google.com/github/muhxz3/Messy-Employee-Dataset-Analysis/blob/main/Day11(DataScienceandAI).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning

###### The process of identifying and correcting inaccurate, incomplete, inconsistent, duplicated or imporoperly formatted data.

In [ ]:
import pandas as pd

In [ ]:
# reading the dataset
data = pd.read_csv('/content/Day11_Messy_Company_Employee_Dataset.csv')
data

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid
...,...,...,...,...,...,...,...,...,...,...,...,...
152,EMP0132,Manya Rao,Marketing,Content Strategist,30.0,Female,49522.0,0.6,2021-11-25,Delhi,2.0,Remote
153,EMP0073,Karan Kapoor,Customer Success,Customer Success Manager,42.0,MALE,43331.0,1.1,2018-03-23,Jaipur,3.0,Hybrid
154,EMP0124,Saira Kapoor,Engineering,QA Engineer,33.0,Male,94812.0,7.2,2024-06-12,Jaipur,4.0,Hybrid
155,EMP0020,Sara Ali,Sales,Sales Executive,22.0,Female,51745.0,2.4,2020-11-19,NaN,2.0,Office
156,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote

#### <u>Missing Value</u>
No vlaue or a missing entry in the dataset
- Detecting using isna() or isnull() function

In [ ]:
data.isna()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,False,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
152,False,False,False,False,False,False,False,False,False,False,False,False
153,False,False,False,False,False,False,False,False,False,False,False,False
154,False,False,False,False,False,False,False,False,False,False,False,False
155,False,False,False,False,False,False,False,False,False,True,False,False
156,False,False,False,False,False,False,False,False,False,False,False,False

##### Quantifying Null Values

In [ ]:
data.isna().sum()

Employee_ID          0
Employee_Name        0
Department           5
Job_Title            0
Age                  4
Gender               5
Annual_Salary        5
Experience_Years     3
Joining_Date         0
City                 5
Performance_Score    3
Work_Mode            2
dtype: int64

In [ ]:
#Total missing values
print(data.isna().sum().sum())

32

#### Finding percentage of missing values

In [ ]:
percent_missing = ((data.isna().sum())/len(data))*100
percent_missing

Employee_ID          0.000000
Employee_Name        0.000000
Department           3.184713
Job_Title            0.000000
Age                  2.547771
Gender               3.184713
Annual_Salary        3.184713
Experience_Years     1.910828
Joining_Date         0.000000
City                 3.184713
Performance_Score    1.910828
Work_Mode            1.273885
dtype: float64

#### MCAR - Missing completely at random
- The missingness has no relationship with the data.
#### MAR - Missing at random
- The missingness is related to other data or variables.
#### MNAR - Missing not at random
- The missingness is completely related to the missing value itself.

### Handling Missing Values

###### 1. Deletion
- Remove the missing observations/ entries
- using dropna() or dropnull() functions
- dropna(subset=["column_names"]) -- dropping rows
- dropna(axis=1) -- dropping rows
- <b>thresh</b> :- df.dropna(thresh=2) -- keep the rows that have atleast 2 non-null values
###### 2. Imputation
- Replace the missing observations or entries with a certain values (mean(), median(), mode(), etc.)
- df.fillna(value)<br>
eg:- df.fillna(0)<br>
df.fillna("N/A")
- fill different values for different columns:- <br>
df.fillna(
  {
    "marks":0,
    "city":"NA"
  }
)
- df["Marks"].fillna(df["marks"].mean())
- llly, median -- mid value
- mode -- the value that appears most of the times.<br>
df["city"].fillna(df["city"].mode())




---

###### forwardfill
- ffill() - fills missing entries with prev values
###### backwardfill
- bfill() - fills missing entries with next values



---

#### Duplicates
- df.duplicated()
- for quantifying:- <br>
df.duplicated().sum()
- delete:- df.drop_duplicates()

In [ ]:
data.head()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [ ]:
data.shape

(157, 12)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        157 non-null    object
 1   Employee_Name      157 non-null    object
 2   Department         152 non-null    object
 3   Job_Title          157 non-null    object
 4   Age                153 non-null    float64
 5   Gender             152 non-null    object
 6   Annual_Salary      152 non-null    float64
 7   Experience_Years   154 non-null    float64
 8   Joining_Date       157 non-null    object
 9   City               152 non-null    object
 10  Performance_Score  154 non-null    float64
 11  Work_Mode          155 non-null    object
dtypes: float64(4), object(8)
memory usage: 14.8+ KB

In [ ]:
data.columns

Index(['Employee_ID', 'Employee_Name', 'Department', 'Job_Title', 'Age',
       'Gender', 'Annual_Salary', 'Experience_Years', 'Joining_Date', 'City',
       'Performance_Score', 'Work_Mode'],
      dtype='object')

In [ ]:
# identifying missing values
data.isna().sum()

Employee_ID          0
Employee_Name        0
Department           5
Job_Title            0
Age                  4
Gender               5
Annual_Salary        5
Experience_Years     3
Joining_Date         0
City                 5
Performance_Score    3
Work_Mode            2
dtype: int64

In [ ]:
data.isna().sum().sum()

np.int64(32)

In [ ]:
# finding the percentage of all the missing values
percent_missing = ((data.isna().sum())/len(data))*100
percent_missing

Employee_ID          0.000000
Employee_Name        0.000000
Department           3.184713
Job_Title            0.000000
Age                  2.547771
Gender               3.184713
Annual_Salary        3.184713
Experience_Years     1.910828
Joining_Date         0.000000
City                 3.184713
Performance_Score    1.910828
Work_Mode            1.273885
dtype: float64

In [ ]:
percent_missing.round(1)

Employee_ID          0.0
Employee_Name        0.0
Department           3.2
Job_Title            0.0
Age                  2.5
Gender               3.2
Annual_Salary        3.2
Experience_Years     1.9
Joining_Date         0.0
City                 3.2
Performance_Score    1.9
Work_Mode            1.3
dtype: float64

In [ ]:
# drop the missing values
data_drop = data.copy()
print("Original Data: ",data_drop.shape)

data_drop = data_drop.dropna()
print("After dropping Data: ",data_drop.shape)

Original Data:  (157, 12)
After dropping Data:  (125, 12)

In [ ]:
data_drop = data.dropna(subset=["City"])
print("After dropping Data: ",data_drop.shape)

After dropping Data:  (152, 12)

In [ ]:
# thresh

data_thresh = data.dropna(thresh=7)
print(data_thresh.shape)

(157, 12)

In [ ]:
# imputation part

data_fill = data.copy()
data_fill["Department"] = data_fill["Department"].fillna("Unknown")
data_fill["Department"].isna().sum()

np.int64(0)

In [ ]:
data_fill["Department"]

0               Unknown
1             Marketing
2       Human Resources
3           Engineering
4                 Sales
             ...
152           Marketing
153    Customer Success
154         Engineering
155               Sales
156           Marketing
Name: Department, Length: 157, dtype: object

In [ ]:
data_fill.isna().sum()

Employee_ID          0
Employee_Name        0
Department           0
Job_Title            0
Age                  4
Gender               5
Annual_Salary        5
Experience_Years     3
Joining_Date         0
City                 5
Performance_Score    3
Work_Mode            2
dtype: int64

In [ ]:
# fillna different values for different columns

data_fill = data.fillna({
    "Age": 18,
    "Annual_Salary": 0
})

In [ ]:
data_fill["Annual_Salary"].isna().sum()

np.int64(0)

In [ ]:
# imputation by mean, median or mode

df_mean = data.copy()
df_mean["Age"] = df_mean["Age"].fillna(df_mean["Age"].mean())
df_mean["Age"].isna().sum()

np.int64(0)

In [ ]:
df_mean["Age"]

0      48.0
1      31.0
2      28.0
3      30.0
4      25.0
       ...
152    30.0
153    42.0
154    33.0
155    22.0
156    52.0
Name: Age, Length: 157, dtype: float64